### ISSUE TITLE
Storage doesn’t allow for Vagrant-based testing

### ISSUE THREAD

**Issue by jeffbyrnes** [evertrue/storage-cookbook#2]
Very early in this cookbook’s convergence, it attempts to perform an operation that will only work properly on an EC2 instance. This prevents any sort of local, non-EC2 testing of this cookbook, or any other that depends upon it.

Example trace/failure:

```
Recipe Compile Error in /tmp/kitchen/cache/cookbooks/et_lids_api/recipes/default.rb
         ================================================================================
       
         
       
  NoMethodError       
         -------------
         
undefined method `[]' for nil:NilClass       
         
         
       Cookbook Trace:
         ---------------
           /tmp/kitchen/cache/cookbooks/storage/libraries/storage.rb:24:in `instance_store_volumes?'
       
           /tmp/kitchen/cache/cookbooks/storage/recipes/default.rb:21:in `from_file'
         
  /tmp/kitchen/cache/cookbooks/et_rails_app/recipes/default.rb:17:in `from_file'       
           /tmp/kitchen/cache/cookbooks/et_lids_api/recipes/default.rb:34:in `from_file'
       
         
         Relevant File Content:
         ----------------------
         /tmp/kitchen/cache/cookbooks/storage/libraries/storage.rb:
         
          17:      end
          18:  
       
   19:      def mnt_device       
          20:        @node['filesystem'].find { |_k, v| v['mount'] == '/mnt' }
          21:      end
          22:  
         
 23:      def instance_store_volumes?       
       
          24>>       f = fog.flavors.get(@node['ec2']['instance_type'])
         
        25:        fail "Unrecognized flavor: #{@node['ec2']['instance_type']}" if f.nil?
       
   26:        !f.instance_store_volumes.zero?       
          27:      end
         
        28:  
       
          29:      def initialize(node)
          30:        @node = node
         
        31:      end
         
        32:  
         
        33:      private
```

**Comment by EdHurtig** [comment]
@jeffbyrnes I believe this issue has been fixed based on my experiences with this cookbook and https://github.com/evertrue/storage-cookbook/blob/master/libraries/storage.rb#L9-L11
